from turtle import *
t=Turtle()
t.speed(1)
sc=Screen()
sc.setup(height=600, width=1000)
sc.title("My Turtle")
#sc.bgcolor('pink')
sc.bgpic('test.gif')
t.shape('turtle')
#t.hideturtle()
# t.pencolor('red')
# t.fillcolor('yellow')
t.pensize(10)
t.color('red','yellow')
t.begin_fill()
t.fd(100)
t.left(90)
t.fd(100)
t.left(90)
t.fd(100)
t.left(90)
t.fd(100)
t.end_fill()

t.penup()  #t.pu()


t.fd(100)
t.pendown()
t.color('green','yellow')
t.begin_fill()
t.forward(100)
t.left(90)
t.fd(100)
t.left(90)
t.fd(100)
t.left(90)
t.fd(100)
t.end_fill()

t.backward(200)

t.write('Mera Bharat Mahan',font=("Comic Sans Ms",25,'bold'))
done()